/* Auto-generated by tools/gen_clips.py. Do not hand-edit. */

const AUDIO_CLIPS = {
  "lead_first_marching_in_place": {
    "file": "audio/clips/lead_first_marching_in_place.m4a",
    "duration": 1.882
  },
  "lead_next_marching_in_place": {
    "file": "audio/clips/lead_next_marching_in_place.m4a",
    "duration": 1.864
  },
  "lead_final_marching_in_place": {
    "file": "audio/clips/lead_final_marching_in_place.m4a",
    "duration": 3.635
  },
  "full_marching_in_place": {
    "file": "audio/clips/full_marching_in_place.m4a",
    "duration": 11.194
  },
  "brief_marching_in_place": {
    "file": "audio/clips/brief_marching_in_place.m4a",
    "duration": 2.524
  },
  "lead_first_bodyweight_squats": {
    "file": "audio/clips/lead_first_bodyweight_squats.m4a",
    "duration": 1.998
  },
  "lead_next_bodyweight_squats": {
    "file": "audio/clips/lead_next_bodyweight_squats.m4a",
    "duration": 1.991
  },
  "lead_final_bodyweight_squats": {
    "file": "audio/clips/lead_final_bodyweight_squats.m4a",
    "duration": 3.751
  },
  "full_bodyweight_squats": {
    "file": "audio/clips/full_bodyweight_squats.m4a",
    "duration": 11.833
  },
  "brief_bodyweight_squats": {
    "file": "audio/clips/brief_bodyweight_squats.m4a",
    "duration": 2.703
  },
  "lead_first_situps": {
    "file": "audio/clips/lead_first_situps.m4a",
    "duration": 1.464
  },
  "lead_next_situps": {
    "file": "audio/clips/lead_next_situps.m4a",
    "duration": 1.446
  },
  "lead_final_situps": {
    "file": "audio/clips/lead_final_situps.m4a",
    "duration": 3.206
  },
  "full_situps": {
    "file": "audio/clips/full_situps.m4a",
    "duration": 14.436
  },
  "brief_situps": {
    "file": "audio/clips/brief_situps.m4a",
    "duration": 2.168
  },
  "lead_first_modified_jumping_jacks": {
    "file": "audio/clips/lead_first_modified_jumping_jacks.m4a",
    "duration": 2.323
  },
  "lead_next_modified_jumping_jacks": {
    "file": "audio/clips/lead_next_modified_jumping_jacks.m4a",
    "duration": 2.305
  },
  "lead_final_modified_jumping_jacks": {
    "file": "audio/clips/lead_final_modified_jumping_jacks.m4a",
    "duration": 4.077
  },
  "full_modified_jumping_jacks": {
    "file": "audio/clips/full_modified_jumping_jacks.m4a",
    "duration": 12.854
  },
  "brief_modified_jumping_jacks": {
    "file": "audio/clips/brief_modified_jumping_jacks.m4a",
    "duration": 2.092
  },
  "lead_first_chest_press_wall": {
    "file": "audio/clips/lead_first_chest_press_wall.m4a",
    "duration": 2.567
  },
  "lead_next_chest_press_wall": {
    "file": "audio/clips/lead_next_chest_press_wall.m4a",
    "duration": 2.549
  },
  "lead_final_chest_press_wall": {
    "file": "audio/clips/lead_final_chest_press_wall.m4a",
    "duration": 4.32
  },
  "full_chest_press_wall": {
    "file": "audio/clips/full_chest_press_wall.m4a",
    "duration": 22.224
  },
  "brief_chest_press_wall": {
    "file": "audio/clips/brief_chest_press_wall.m4a",
    "duration": 2.204
  },
  "lead_first_jumping_jacks": {
    "file": "audio/clips/lead_first_jumping_jacks.m4a",
    "duration": 1.766
  },
  "lead_next_jumping_jacks": {
    "file": "audio/clips/lead_next_jumping_jacks.m4a",
    "duration": 1.748
  },
  "lead_final_jumping_jacks": {
    "file": "audio/clips/lead_final_jumping_jacks.m4a",
    "duration": 3.519
  },
  "full_jumping_jacks": {
    "file": "audio/clips/full_jumping_jacks.m4a",
    "duration": 10.486
  },
  "brief_jumping_jacks": {
    "file": "audio/clips/brief_jumping_jacks.m4a",
    "duration": 2.347
  },
  "lead_first_high_knees": {
    "file": "audio/clips/lead_first_high_knees.m4a",
    "duration": 1.522
  },
  "lead_next_high_knees": {
    "file": "audio/clips/lead_next_high_knees.m4a",
    "duration": 1.504
  },
  "lead_final_high_knees": {
    "file": "audio/clips/lead_final_high_knees.m4a",
    "duration": 3.275
  },
  "full_high_knees": {
    "file": "audio/clips/full_high_knees.m4a",
    "duration": 9.964
  },
  "brief_high_knees": {
    "file": "audio/clips/brief_high_knees.m4a",
    "duration": 1.931
  },
  "lead_first_speed_skaters": {
    "file": "audio/clips/lead_first_speed_skaters.m4a",
    "duration": 1.801
  },
  "lead_next_speed_skaters": {
    "file": "audio/clips/lead_next_speed_skaters.m4a",
    "duration": 1.782
  },
  "lead_final_speed_skaters": {
    "file": "audio/clips/lead_final_speed_skaters.m4a",
    "duration": 3.554
  },
  "full_speed_skaters": {
    "file": "audio/clips/full_speed_skaters.m4a",
    "duration": 12.169
  },
  "brief_speed_skaters": {
    "file": "audio/clips/brief_speed_skaters.m4a",
    "duration": 2.094
  },
  "lead_first_chest_press_incline": {
    "file": "audio/clips/lead_first_chest_press_incline.m4a",
    "duration": 2.858
  },
  "lead_next_chest_press_incline": {
    "file": "audio/clips/lead_next_chest_press_incline.m4a",
    "duration": 2.851
  },
  "lead_final_chest_press_incline": {
    "file": "audio/clips/lead_final_chest_press_incline.m4a",
    "duration": 4.611
  },
  "full_chest_press_incline": {
    "file": "audio/clips/full_chest_press_incline.m4a",
    "duration": 18.748
  },
  "brief_chest_press_incline": {
    "file": "audio/clips/brief_chest_press_incline.m4a",
    "duration": 2.25
  },
  "lead_first_burpees": {
    "file": "audio/clips/lead_first_burpees.m4a",
    "duration": 1.429
  },
  "lead_next_burpees": {
    "file": "audio/clips/lead_next_burpees.m4a",
    "duration": 1.423
  },
  "lead_final_burpees": {
    "file": "audio/clips/lead_final_burpees.m4a",
    "duration": 3.183
  },
  "full_burpees": {
    "file": "audio/clips/full_burpees.m4a",
    "duration": 15.235
  },
  "brief_burpees": {
    "file": "audio/clips/brief_burpees.m4a",
    "duration": 1.96
  },
  "lead_first_jump_squats": {
    "file": "audio/clips/lead_first_jump_squats.m4a",
    "duration": 1.731
  },
  "lead_next_jump_squats": {
    "file": "audio/clips/lead_next_jump_squats.m4a",
    "duration": 1.713
  },
  "lead_final_jump_squats": {
    "file": "audio/clips/lead_final_jump_squats.m4a",
    "duration": 3.484
  },
  "full_jump_squats": {
    "file": "audio/clips/full_jump_squats.m4a",
    "duration": 11.798
  },
  "brief_jump_squats": {
    "file": "audio/clips/brief_jump_squats.m4a",
    "duration": 2.11
  },
  "lead_first_mountain_climbers": {
    "file": "audio/clips/lead_first_mountain_climbers.m4a",
    "duration": 1.917
  },
  "lead_next_mountain_climbers": {
    "file": "audio/clips/lead_next_mountain_climbers.m4a",
    "duration": 1.899
  },
  "lead_final_mountain_climbers": {
    "file": "audio/clips/lead_final_mountain_climbers.m4a",
    "duration": 3.659
  },
  "full_mountain_climbers": {
    "file": "audio/clips/full_mountain_climbers.m4a",
    "duration": 11.612
  },
  "brief_mountain_climbers": {
    "file": "audio/clips/brief_mountain_climbers.m4a",
    "duration": 1.838
  },
  "lead_first_chest_press_floor": {
    "file": "audio/clips/lead_first_chest_press_floor.m4a",
    "duration": 2.637
  },
  "lead_next_chest_press_floor": {
    "file": "audio/clips/lead_next_chest_press_floor.m4a",
    "duration": 2.618
  },
  "lead_final_chest_press_floor": {
    "file": "audio/clips/lead_final_chest_press_floor.m4a",
    "duration": 4.378
  },
  "full_chest_press_floor": {
    "file": "audio/clips/full_chest_press_floor.m4a",
    "duration": 13.4
  },
  "brief_chest_press_floor": {
    "file": "audio/clips/brief_chest_press_floor.m4a",
    "duration": 2.396
  },
  "lead_first_superman_holds": {
    "file": "audio/clips/lead_first_superman_holds.m4a",
    "duration": 1.917
  },
  "lead_next_superman_holds": {
    "file": "audio/clips/lead_next_superman_holds.m4a",
    "duration": 1.899
  },
  "lead_final_superman_holds": {
    "file": "audio/clips/lead_final_superman_holds.m4a",
    "duration": 3.67
  },
  "full_superman_holds": {
    "file": "audio/clips/full_superman_holds.m4a",
    "duration": 14.157
  },
  "brief_superman_holds": {
    "file": "audio/clips/brief_superman_holds.m4a",
    "duration": 2.349
  },
  "lead_first_prone_t_raises": {
    "file": "audio/clips/lead_first_prone_t_raises.m4a",
    "duration": 1.871
  },
  "lead_next_prone_t_raises": {
    "file": "audio/clips/lead_next_prone_t_raises.m4a",
    "duration": 1.852
  },
  "lead_final_prone_t_raises": {
    "file": "audio/clips/lead_final_prone_t_raises.m4a",
    "duration": 3.624
  },
  "full_prone_t_raises": {
    "file": "audio/clips/full_prone_t_raises.m4a",
    "duration": 10.906
  },
  "brief_prone_t_raises": {
    "file": "audio/clips/brief_prone_t_raises.m4a",
    "duration": 2.22
  },
  "lead_first_bird_dogs": {
    "file": "audio/clips/lead_first_bird_dogs.m4a",
    "duration": 1.58
  },
  "lead_next_bird_dogs": {
    "file": "audio/clips/lead_next_bird_dogs.m4a",
    "duration": 1.562
  },
  "lead_final_bird_dogs": {
    "file": "audio/clips/lead_final_bird_dogs.m4a",
    "duration": 3.334
  },
  "full_bird_dogs": {
    "file": "audio/clips/full_bird_dogs.m4a",
    "duration": 11.891
  },
  "brief_bird_dogs": {
    "file": "audio/clips/brief_bird_dogs.m4a",
    "duration": 2.351
  },
  "lead_first_glute_bridges": {
    "file": "audio/clips/lead_first_glute_bridges.m4a",
    "duration": 1.592
  },
  "lead_next_glute_bridges": {
    "file": "audio/clips/lead_next_glute_bridges.m4a",
    "duration": 1.574
  },
  "lead_final_glute_bridges": {
    "file": "audio/clips/lead_final_glute_bridges.m4a",
    "duration": 3.345
  },
  "full_glute_bridges": {
    "file": "audio/clips/full_glute_bridges.m4a",
    "duration": 11.208
  },
  "brief_glute_bridges": {
    "file": "audio/clips/brief_glute_bridges.m4a",
    "duration": 2.243
  },
  "lead_first_quadruped_arm_raises": {
    "file": "audio/clips/lead_first_quadruped_arm_raises.m4a",
    "duration": 2.231
  },
  "lead_next_quadruped_arm_raises": {
    "file": "audio/clips/lead_next_quadruped_arm_raises.m4a",
    "duration": 2.212
  },
  "lead_final_quadruped_arm_raises": {
    "file": "audio/clips/lead_final_quadruped_arm_raises.m4a",
    "duration": 3.984
  },
  "full_quadruped_arm_raises": {
    "file": "audio/clips/full_quadruped_arm_raises.m4a",
    "duration": 10.764
  },
  "brief_quadruped_arm_raises": {
    "file": "audio/clips/brief_quadruped_arm_raises.m4a",
    "duration": 2.289
  },
  "lead_first_supermans_pulse": {
    "file": "audio/clips/lead_first_supermans_pulse.m4a",
    "duration": 2.207
  },
  "lead_next_supermans_pulse": {
    "file": "audio/clips/lead_next_supermans_pulse.m4a",
    "duration": 2.189
  },
  "lead_final_supermans_pulse": {
    "file": "audio/clips/lead_final_supermans_pulse.m4a",
    "duration": 3.949
  },
  "full_supermans_pulse": {
    "file": "audio/clips/full_supermans_pulse.m4a",
    "duration": 13.123
  },
  "brief_supermans_pulse": {
    "file": "audio/clips/brief_supermans_pulse.m4a",
    "duration": 2.533
  },
  "lead_first_prone_iyt_raises": {
    "file": "audio/clips/lead_first_prone_iyt_raises.m4a",
    "duration": 2.254
  },
  "lead_next_prone_iyt_raises": {
    "file": "audio/clips/lead_next_prone_iyt_raises.m4a",
    "duration": 2.247
  },
  "lead_final_prone_iyt_raises": {
    "file": "audio/clips/lead_final_prone_iyt_raises.m4a",
    "duration": 4.007
  },
  "full_prone_iyt_raises": {
    "file": "audio/clips/full_prone_iyt_raises.m4a",
    "duration": 12.868
  },
  "brief_prone_iyt_raises": {
    "file": "audio/clips/brief_prone_iyt_raises.m4a",
    "duration": 3.027
  },
  "lead_first_plank_shoulder_taps": {
    "file": "audio/clips/lead_first_plank_shoulder_taps.m4a",
    "duration": 2.138
  },
  "lead_next_plank_shoulder_taps": {
    "file": "audio/clips/lead_next_plank_shoulder_taps.m4a",
    "duration": 2.119
  },
  "lead_final_plank_shoulder_taps": {
    "file": "audio/clips/lead_final_plank_shoulder_taps.m4a",
    "duration": 3.879
  },
  "full_plank_shoulder_taps": {
    "file": "audio/clips/full_plank_shoulder_taps.m4a",
    "duration": 11.937
  },
  "brief_plank_shoulder_taps": {
    "file": "audio/clips/brief_plank_shoulder_taps.m4a",
    "duration": 2.322
  },
  "lead_first_reverse_snow_angels": {
    "file": "audio/clips/lead_first_reverse_snow_angels.m4a",
    "duration": 2.08
  },
  "lead_next_reverse_snow_angels": {
    "file": "audio/clips/lead_next_reverse_snow_angels.m4a",
    "duration": 2.061
  },
  "lead_final_reverse_snow_angels": {
    "file": "audio/clips/lead_final_reverse_snow_angels.m4a",
    "duration": 3.833
  },
  "full_reverse_snow_angels": {
    "file": "audio/clips/full_reverse_snow_angels.m4a",
    "duration": 12.694
  },
  "brief_reverse_snow_angels": {
    "file": "audio/clips/brief_reverse_snow_angels.m4a",
    "duration": 2.371
  },
  "lead_first_bird_dogs_slow": {
    "file": "audio/clips/lead_first_bird_dogs_slow.m4a",
    "duration": 2.451
  },
  "lead_next_bird_dogs_slow": {
    "file": "audio/clips/lead_next_bird_dogs_slow.m4a",
    "duration": 2.433
  },
  "lead_final_bird_dogs_slow": {
    "file": "audio/clips/lead_final_bird_dogs_slow.m4a",
    "duration": 4.193
  },
  "full_bird_dogs_slow": {
    "file": "audio/clips/full_bird_dogs_slow.m4a",
    "duration": 12.843
  },
  "brief_bird_dogs_slow": {
    "file": "audio/clips/brief_bird_dogs_slow.m4a",
    "duration": 2.736
  },
  "lead_first_inverted_rows": {
    "file": "audio/clips/lead_first_inverted_rows.m4a",
    "duration": 1.731
  },
  "lead_next_inverted_rows": {
    "file": "audio/clips/lead_next_inverted_rows.m4a",
    "duration": 1.713
  },
  "lead_final_inverted_rows": {
    "file": "audio/clips/lead_final_inverted_rows.m4a",
    "duration": 3.484
  },
  "full_inverted_rows": {
    "file": "audio/clips/full_inverted_rows.m4a",
    "duration": 11.997
  },
  "brief_inverted_rows": {
    "file": "audio/clips/brief_inverted_rows.m4a",
    "duration": 2.076
  },
  "lead_first_commandos": {
    "file": "audio/clips/lead_first_commandos.m4a",
    "duration": 1.58
  },
  "lead_next_commandos": {
    "file": "audio/clips/lead_next_commandos.m4a",
    "duration": 1.562
  },
  "lead_final_commandos": {
    "file": "audio/clips/lead_final_commandos.m4a",
    "duration": 3.334
  },
  "full_commandos": {
    "file": "audio/clips/full_commandos.m4a",
    "duration": 11.937
  },
  "brief_commandos": {
    "file": "audio/clips/brief_commandos.m4a",
    "duration": 2.318
  },
  "lead_first_renegade_row_holds": {
    "file": "audio/clips/lead_first_renegade_row_holds.m4a",
    "duration": 2.486
  },
  "lead_next_renegade_row_holds": {
    "file": "audio/clips/lead_next_renegade_row_holds.m4a",
    "duration": 2.467
  },
  "lead_final_renegade_row_holds": {
    "file": "audio/clips/lead_final_renegade_row_holds.m4a",
    "duration": 4.227
  },
  "full_renegade_row_holds": {
    "file": "audio/clips/full_renegade_row_holds.m4a",
    "duration": 11.473
  },
  "brief_renegade_row_holds": {
    "file": "audio/clips/brief_renegade_row_holds.m4a",
    "duration": 1.711
  },
  "lead_first_plank_to_downward_dog": {
    "file": "audio/clips/lead_first_plank_to_downward_dog.m4a",
    "duration": 2.114
  },
  "lead_next_plank_to_downward_dog": {
    "file": "audio/clips/lead_next_plank_to_downward_dog.m4a",
    "duration": 2.108
  },
  "lead_final_plank_to_downward_dog": {
    "file": "audio/clips/lead_final_plank_to_downward_dog.m4a",
    "duration": 3.868
  },
  "full_plank_to_downward_dog": {
    "file": "audio/clips/full_plank_to_downward_dog.m4a",
    "duration": 10.474
  },
  "brief_plank_to_downward_dog": {
    "file": "audio/clips/brief_plank_to_downward_dog.m4a",
    "duration": 2.19
  },
  "lead_first_superman_swimmers": {
    "file": "audio/clips/lead_first_superman_swimmers.m4a",
    "duration": 2.01
  },
  "lead_next_superman_swimmers": {
    "file": "audio/clips/lead_next_superman_swimmers.m4a",
    "duration": 2.003
  },
  "lead_final_superman_swimmers": {
    "file": "audio/clips/lead_final_superman_swimmers.m4a",
    "duration": 3.763
  },
  "full_superman_swimmers": {
    "file": "audio/clips/full_superman_swimmers.m4a",
    "duration": 11.068
  },
  "brief_superman_swimmers": {
    "file": "audio/clips/brief_superman_swimmers.m4a",
    "duration": 2.418
  },
  "lead_first_wall_pushups": {
    "file": "audio/clips/lead_first_wall_pushups.m4a",
    "duration": 1.778
  },
  "lead_next_wall_pushups": {
    "file": "audio/clips/lead_next_wall_pushups.m4a",
    "duration": 1.759
  },
  "lead_final_wall_pushups": {
    "file": "audio/clips/lead_final_wall_pushups.m4a",
    "duration": 3.531
  },
  "full_wall_pushups": {
    "file": "audio/clips/full_wall_pushups.m4a",
    "duration": 13.539
  },
  "brief_wall_pushups": {
    "file": "audio/clips/brief_wall_pushups.m4a",
    "duration": 1.995
  },
  "lead_first_forward_lunges": {
    "file": "audio/clips/lead_first_forward_lunges.m4a",
    "duration": 1.859
  },
  "lead_next_forward_lunges": {
    "file": "audio/clips/lead_next_forward_lunges.m4a",
    "duration": 1.852
  },
  "lead_final_forward_lunges": {
    "file": "audio/clips/lead_final_forward_lunges.m4a",
    "duration": 3.612
  },
  "full_forward_lunges": {
    "file": "audio/clips/full_forward_lunges.m4a",
    "duration": 13.203
  },
  "brief_forward_lunges": {
    "file": "audio/clips/brief_forward_lunges.m4a",
    "duration": 2.347
  },
  "lead_first_dead_bugs": {
    "file": "audio/clips/lead_first_dead_bugs.m4a",
    "duration": 1.604
  },
  "lead_next_dead_bugs": {
    "file": "audio/clips/lead_next_dead_bugs.m4a",
    "duration": 1.585
  },
  "lead_final_dead_bugs": {
    "file": "audio/clips/lead_final_dead_bugs.m4a",
    "duration": 3.357
  },
  "full_dead_bugs": {
    "file": "audio/clips/full_dead_bugs.m4a",
    "duration": 13.39
  },
  "brief_dead_bugs": {
    "file": "audio/clips/brief_dead_bugs.m4a",
    "duration": 2.642
  },
  "lead_first_pushups": {
    "file": "audio/clips/lead_first_pushups.m4a",
    "duration": 1.488
  },
  "lead_next_pushups": {
    "file": "audio/clips/lead_next_pushups.m4a",
    "duration": 1.469
  },
  "lead_final_pushups": {
    "file": "audio/clips/lead_final_pushups.m4a",
    "duration": 3.241
  },
  "full_pushups": {
    "file": "audio/clips/full_pushups.m4a",
    "duration": 12.251
  },
  "brief_pushups": {
    "file": "audio/clips/brief_pushups.m4a",
    "duration": 2.928
  },
  "lead_first_split_squats": {
    "file": "audio/clips/lead_first_split_squats.m4a",
    "duration": 1.813
  },
  "lead_next_split_squats": {
    "file": "audio/clips/lead_next_split_squats.m4a",
    "duration": 1.806
  },
  "lead_final_split_squats": {
    "file": "audio/clips/lead_final_split_squats.m4a",
    "duration": 3.566
  },
  "full_split_squats": {
    "file": "audio/clips/full_split_squats.m4a",
    "duration": 12.634
  },
  "brief_split_squats": {
    "file": "audio/clips/brief_split_squats.m4a",
    "duration": 2.22
  },
  "lead_first_plank_hold": {
    "file": "audio/clips/lead_first_plank_hold.m4a",
    "duration": 1.557
  },
  "lead_next_plank_hold": {
    "file": "audio/clips/lead_next_plank_hold.m4a",
    "duration": 1.539
  },
  "lead_final_plank_hold": {
    "file": "audio/clips/lead_final_plank_hold.m4a",
    "duration": 3.31
  },
  "full_plank_hold": {
    "file": "audio/clips/full_plank_hold.m4a",
    "duration": 12.889
  },
  "brief_plank_hold": {
    "file": "audio/clips/brief_plank_hold.m4a",
    "duration": 2.672
  },
  "lead_first_lateral_lunges": {
    "file": "audio/clips/lead_first_lateral_lunges.m4a",
    "duration": 1.847
  },
  "lead_next_lateral_lunges": {
    "file": "audio/clips/lead_next_lateral_lunges.m4a",
    "duration": 1.841
  },
  "lead_final_lateral_lunges": {
    "file": "audio/clips/lead_final_lateral_lunges.m4a",
    "duration": 3.601
  },
  "full_lateral_lunges": {
    "file": "audio/clips/full_lateral_lunges.m4a",
    "duration": 11.426
  },
  "brief_lateral_lunges": {
    "file": "audio/clips/brief_lateral_lunges.m4a",
    "duration": 2.233
  },
  "lead_first_tricep_dips_chair": {
    "file": "audio/clips/lead_first_tricep_dips_chair.m4a",
    "duration": 2.474
  },
  "lead_next_tricep_dips_chair": {
    "file": "audio/clips/lead_next_tricep_dips_chair.m4a",
    "duration": 2.456
  },
  "lead_final_tricep_dips_chair": {
    "file": "audio/clips/lead_final_tricep_dips_chair.m4a",
    "duration": 4.227
  },
  "full_tricep_dips_chair": {
    "file": "audio/clips/full_tricep_dips_chair.m4a",
    "duration": 14.98
  },
  "brief_tricep_dips_chair": {
    "file": "audio/clips/brief_tricep_dips_chair.m4a",
    "duration": 2.491
  },
  "lead_first_burpee_pushups": {
    "file": "audio/clips/lead_first_burpee_pushups.m4a",
    "duration": 1.847
  },
  "lead_next_burpee_pushups": {
    "file": "audio/clips/lead_next_burpee_pushups.m4a",
    "duration": 1.829
  },
  "lead_final_burpee_pushups": {
    "file": "audio/clips/lead_final_burpee_pushups.m4a",
    "duration": 3.601
  },
  "full_burpee_pushups": {
    "file": "audio/clips/full_burpee_pushups.m4a",
    "duration": 12.227
  },
  "brief_burpee_pushups": {
    "file": "audio/clips/brief_burpee_pushups.m4a",
    "duration": 2.297
  },
  "lead_first_jump_lunges": {
    "file": "audio/clips/lead_first_jump_lunges.m4a",
    "duration": 1.685
  },
  "lead_next_jump_lunges": {
    "file": "audio/clips/lead_next_jump_lunges.m4a",
    "duration": 1.678
  },
  "lead_final_jump_lunges": {
    "file": "audio/clips/lead_final_jump_lunges.m4a",
    "duration": 3.438
  },
  "full_jump_lunges": {
    "file": "audio/clips/full_jump_lunges.m4a",
    "duration": 12.599
  },
  "brief_jump_lunges": {
    "file": "audio/clips/brief_jump_lunges.m4a",
    "duration": 2.139
  },
  "lead_first_pike_pushups": {
    "file": "audio/clips/lead_first_pike_pushups.m4a",
    "duration": 1.778
  },
  "lead_next_pike_pushups": {
    "file": "audio/clips/lead_next_pike_pushups.m4a",
    "duration": 1.759
  },
  "lead_final_pike_pushups": {
    "file": "audio/clips/lead_final_pike_pushups.m4a",
    "duration": 3.531
  },
  "full_pike_pushups": {
    "file": "audio/clips/full_pike_pushups.m4a",
    "duration": 13.899
  },
  "brief_pike_pushups": {
    "file": "audio/clips/brief_pike_pushups.m4a",
    "duration": 2.353
  },
  "lead_first_single_leg_glute_bridges": {
    "file": "audio/clips/lead_first_single_leg_glute_bridges.m4a",
    "duration": 2.231
  },
  "lead_next_single_leg_glute_bridges": {
    "file": "audio/clips/lead_next_single_leg_glute_bridges.m4a",
    "duration": 2.212
  },
  "lead_final_single_leg_glute_bridges": {
    "file": "audio/clips/lead_final_single_leg_glute_bridges.m4a",
    "duration": 3.984
  },
  "full_single_leg_glute_bridges": {
    "file": "audio/clips/full_single_leg_glute_bridges.m4a",
    "duration": 12.241
  },
  "brief_single_leg_glute_bridges": {
    "file": "audio/clips/brief_single_leg_glute_bridges.m4a",
    "duration": 2.266
  },
  "lead_first_plank_jacks": {
    "file": "audio/clips/lead_first_plank_jacks.m4a",
    "duration": 1.72
  },
  "lead_next_plank_jacks": {
    "file": "audio/clips/lead_next_plank_jacks.m4a",
    "duration": 1.701
  },
  "lead_final_plank_jacks": {
    "file": "audio/clips/lead_final_plank_jacks.m4a",
    "duration": 3.473
  },
  "full_plank_jacks": {
    "file": "audio/clips/full_plank_jacks.m4a",
    "duration": 9.046
  },
  "brief_plank_jacks": {
    "file": "audio/clips/brief_plank_jacks.m4a",
    "duration": 2.196
  },
  "stretch_name_stretch_quad_right": {
    "file": "audio/clips/stretch_name_stretch_quad_right.m4a",
    "duration": 1.941
  },
  "stretch_script_stretch_quad_right": {
    "file": "audio/clips/stretch_script_stretch_quad_right.m4a",
    "duration": 11.23
  },
  "stretch_name_stretch_quad_left": {
    "file": "audio/clips/stretch_name_stretch_quad_left.m4a",
    "duration": 1.999
  },
  "stretch_script_stretch_quad_left": {
    "file": "audio/clips/stretch_script_stretch_quad_left.m4a",
    "duration": 5.854
  },
  "stretch_name_stretch_hamstring": {
    "file": "audio/clips/stretch_name_stretch_hamstring.m4a",
    "duration": 1.146
  },
  "stretch_script_stretch_hamstring": {
    "file": "audio/clips/stretch_script_stretch_hamstring.m4a",
    "duration": 11.334
  },
  "stretch_name_stretch_chest": {
    "file": "audio/clips/stretch_name_stretch_chest.m4a",
    "duration": 0.88
  },
  "stretch_script_stretch_chest": {
    "file": "audio/clips/stretch_script_stretch_chest.m4a",
    "duration": 9.651
  },
  "stretch_name_stretch_shoulder_right": {
    "file": "audio/clips/stretch_name_stretch_shoulder_right.m4a",
    "duration": 1.589
  },
  "stretch_script_stretch_shoulder_right": {
    "file": "audio/clips/stretch_script_stretch_shoulder_right.m4a",
    "duration": 8.225
  },
  "stretch_name_stretch_shoulder_left": {
    "file": "audio/clips/stretch_name_stretch_shoulder_left.m4a",
    "duration": 1.647
  },
  "stretch_script_stretch_shoulder_left": {
    "file": "audio/clips/stretch_script_stretch_shoulder_left.m4a",
    "duration": 4.136
  },
  "stretch_name_stretch_cobra": {
    "file": "audio/clips/stretch_name_stretch_cobra.m4a",
    "duration": 0.973
  },
  "stretch_script_stretch_cobra": {
    "file": "audio/clips/stretch_script_stretch_cobra.m4a",
    "duration": 10.337
  },
  "stretch_name_stretch_childs_pose": {
    "file": "audio/clips/stretch_name_stretch_childs_pose.m4a",
    "duration": 0.927
  },
  "stretch_script_stretch_childs_pose": {
    "file": "audio/clips/stretch_script_stretch_childs_pose.m4a",
    "duration": 7.588
  },
  "stretch_name_stretch_cat_cow": {
    "file": "audio/clips/stretch_name_stretch_cat_cow.m4a",
    "duration": 0.673
  },
  "stretch_script_stretch_cat_cow": {
    "file": "audio/clips/stretch_script_stretch_cat_cow.m4a",
    "duration": 7.785
  },
  "stretch_name_stretch_spinal_twist_right": {
    "file": "audio/clips/stretch_name_stretch_spinal_twist_right.m4a",
    "duration": 1.942
  },
  "stretch_script_stretch_spinal_twist_right": {
    "file": "audio/clips/stretch_script_stretch_spinal_twist_right.m4a",
    "duration": 10.15
  },
  "stretch_name_stretch_spinal_twist_left": {
    "file": "audio/clips/stretch_name_stretch_spinal_twist_left.m4a",
    "duration": 2.0
  },
  "stretch_script_stretch_spinal_twist_left": {
    "file": "audio/clips/stretch_script_stretch_spinal_twist_left.m4a",
    "duration": 7.573
  },
  "get_ready": {
    "file": "audio/clips/get_ready.m4a",
    "duration": 0.596
  },
  "rest": {
    "file": "audio/clips/rest.m4a",
    "duration": 0.448
  },
  "go": {
    "file": "audio/clips/go.m4a",
    "duration": 0.377
  },
  "halfway": {
    "file": "audio/clips/halfway.m4a",
    "duration": 0.646
  },
  "five_seconds": {
    "file": "audio/clips/five_seconds.m4a",
    "duration": 0.988
  },
  "count_three": {
    "file": "audio/clips/count_three.m4a",
    "duration": 0.432
  },
  "count_two": {
    "file": "audio/clips/count_two.m4a",
    "duration": 0.363
  },
  "count_one": {
    "file": "audio/clips/count_one.m4a",
    "duration": 0.42
  },
  "round_complete": {
    "file": "audio/clips/round_complete.m4a",
    "duration": 3.618
  },
  "thirty_seconds": {
    "file": "audio/clips/thirty_seconds.m4a",
    "duration": 1.0
  },
  "next_round_soon": {
    "file": "audio/clips/next_round_soon.m4a",
    "duration": 1.539
  },
  "workout_complete": {
    "file": "audio/clips/workout_complete.m4a",
    "duration": 2.243
  },
  "relax_breathe": {
    "file": "audio/clips/relax_breathe.m4a",
    "duration": 1.54
  },
  "stretching_complete": {
    "file": "audio/clips/stretching_complete.m4a",
    "duration": 2.348
  },
  "voice_test": {
    "file": "audio/clips/voice_test.m4a",
    "duration": 2.564
  }
};
